import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavMenu from "@/_components/navMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Entry Logger",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <NavMenu/>
        {children}
      </body>
    </html>
  );
}
